export interface Product {
  id: string;
  name: string;
  price: number;
  priceStr: string;
  image: string;
  colors: string[];
  colorNames: string[];
  sizes?: string[];
  isNew: boolean;
  category: string;
  description: string;
  images: string[];
}

export const allProducts: Product[] = [
  // Bikinis
  {
    id: "prod_1",
    name: "The Monaco Triangle Set",
    price: 220,
    priceStr: "$220",
    image: "/images/product_bestseller_1_1776081629759.png",
    images: ["/images/product_bestseller_1_1776081629759.png", "/images/product_bestseller_2_1776081693616.png"],
    colors: ["bg-stone-900", "bg-white", "bg-[#b09165]"],
    colorNames: ["Noir", "Blanc", "Sable"],
    isNew: false,
    category: "Bikinis",
    description: "The Monaco Triangle Set is our signature piece. Crafted from premium Italian sustainable fabric featuring a classic triangle cut and adjustable ties for the perfect fit.",
  },
  {
    id: "prod_2",
    name: "The Capri Ruffle Top",
    price: 140,
    priceStr: "$140",
    image: "/images/category_bikini_1776081526337.png",
    images: ["/images/category_bikini_1776081526337.png"],
    colors: ["bg-stone-100", "bg-[#c6a87c]"],
    colorNames: ["Cream", "Bronze"],
    isNew: false,
    category: "Bikinis",
    description: "Flirty and supportive, the Capri Ruffle Top features delicately layered ruffles and underwire support for enhanced shape.",
  },
  {
    id: "prod_3",
    name: "The Ibiza String Set",
    price: 195,
    priceStr: "$195",
    image: "/images/category_one_piece_1776081471457.png",
    images: ["/images/category_one_piece_1776081471457.png"],
    colors: ["bg-[#1c1917]", "bg-[#f5f3f0]"],
    colorNames: ["Obsidian", "Pearl"],
    isNew: true,
    category: "Bikinis",
    description: "A minimalist dream. The Ibiza String Set features ultra-thin, durable ties and a seamless finish that sits smoothly against the skin.",
  },

  // One Pieces
  {
    id: "prod_4",
    name: "The Amalfi Cut-Out One Piece",
    price: 280,
    priceStr: "$280",
    image: "/images/product_bestseller_2_1776081693616.png",
    images: ["/images/product_bestseller_2_1776081693616.png"],
    colors: ["bg-[#8aa38c]", "bg-stone-900"],
    colorNames: ["Olive", "Noir"],
    isNew: true,
    category: "One Pieces",
    description: "A striking asymmetrical cut-out design that flatters every curve. The Amalfi One Piece provides moderate coverage while maintaining a bold, contemporary look.",
  },
  {
    id: "prod_5",
    name: "The Santorini Plunge",
    price: 260,
    priceStr: "$260",
    image: "/images/category_one_piece_1776081471457.png",
    images: ["/images/category_one_piece_1776081471457.png"],
    colors: ["bg-white", "bg-stone-900"],
    colorNames: ["Blanc", "Noir"],
    isNew: false,
    category: "One Pieces",
    description: "A deep plunge V-neck one piece with a low back. Elegant, timeless, and effortlessly chic.",
  },

  // Resortwear & Kaftans
  {
    id: "prod_6",
    name: "The Positano Silk Kaftan",
    price: 340,
    priceStr: "$340",
    image: "/images/category_resortwear_1776341899337.png",
    images: ["/images/category_resortwear_1776341899337.png"],
    colors: ["bg-white", "bg-[#e8dcc4]"],
    colorNames: ["Silk White", "Sand"],
    isNew: true,
    category: "Kaftans",
    description: "A flowing pure silk kaftan. Perfectly drapes over your swimwear for sunset cocktails.",
  },
  {
    id: "prod_7",
    name: "The St. Barts Linen Set",
    price: 290,
    priceStr: "$290",
    image: "/images/category_resortwear_1776341899337.png",
    images: ["/images/category_resortwear_1776341899337.png"],
    colors: ["bg-stone-100", "bg-stone-900"],
    colorNames: ["Linen", "Midnight"],
    isNew: false,
    category: "Resortwear",
    description: "A two-piece lightweight Italian linen matching set, featuring high-waisted wide leg trousers and an airy crop top.",
  },

  // Cover-Ups & Sarongs
  {
    id: "prod_8",
    name: "The Mykonos Sheer Cover-Up",
    price: 180,
    priceStr: "$180",
    image: "/images/category_coverups_1776081563632.png",
    images: ["/images/category_coverups_1776081563632.png"],
    colors: ["bg-[#e8dcc4]"],
    colorNames: ["Sand"],
    isNew: false,
    category: "Cover-Ups",
    description: "An elegant, sheer mesh cover-up that adds a touch of mystery while keeping things effortless.",
  },
  {
    id: "prod_9",
    name: "The Maldives Silk Sarong",
    price: 110,
    priceStr: "$110",
    image: "/images/category_coverups_1776081563632.png",
    images: ["/images/category_coverups_1776081563632.png"],
    colors: ["bg-[#c6a87c]", "bg-white"],
    colorNames: ["Bronze", "Blanc"],
    isNew: true,
    category: "Sarongs",
    description: "The ultimate beach-to-bar accessory. Our Maldives Sarong is cut from 100% lightweight silk chiffon.",
  },

  // Rash Guards & Swim Shorts
  {
    id: "prod_10",
    name: "The Bondi Rash Guard",
    price: 155,
    priceStr: "$155",
    image: "/images/product_bestseller_2_1776081693616.png",
    images: ["/images/product_bestseller_2_1776081693616.png"],
    colors: ["bg-stone-900", "bg-stone-100"],
    colorNames: ["Noir", "Cream"],
    isNew: true,
    category: "Rash Guards",
    description: "Sleek, UPF 50+ sun protection. Designed to perform in the water while maintaining a luxury athletic silhouette.",
  },
  {
    id: "prod_11",
    name: "The Tulum Swim Shorts",
    price: 130,
    priceStr: "$130",
    image: "/images/product_bestseller_1_1776081629759.png",
    images: ["/images/product_bestseller_1_1776081629759.png"],
    colors: ["bg-[#8aa38c]", "bg-stone-800"],
    colorNames: ["Olive", "Charcoal"],
    isNew: false,
    category: "Swim Shorts",
    description: "Ultra-fast drying, tailored swim shorts perfect for an active day by the pool.",
  },

  // Kids Swimwear
  {
    id: "prod_12",
    name: "Le Petit Sun Suit",
    price: 95,
    priceStr: "$95",
    image: "/images/category_kids_1776342027791.png",
    images: ["/images/category_kids_1776342027791.png"],
    colors: ["bg-[#fef08a]", "bg-[#bfdbfe]"],
    colorNames: ["Lemon", "Sky"],
    isNew: true,
    category: "Kids Swimwear",
    description: "Adorable, full-coverage SPF50 sun suit for the little ones. Built with the same premium fabrics as our adult line.",
  },
  {
    id: "prod_13",
    name: "Mini Amalfi One Piece",
    price: 85,
    priceStr: "$85",
    image: "/images/category_kids_1776342027791.png",
    images: ["/images/category_kids_1776342027791.png"],
    colors: ["bg-[#fbcfe8]", "bg-white"],
    colorNames: ["Rose", "Blanc"],
    isNew: false,
    category: "Kids Swimwear",
    description: "A comfortable, stretchy, and beautifully crafted one-piece for kids.",
  },

  // Towels & Pool Accessories
  {
    id: "prod_14",
    name: "The Riviera Cabana Towel",
    price: 120,
    priceStr: "$120",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-200", "bg-[#b09165]"],
    colorNames: ["Classic Stripe", "Gold Stripe"],
    isNew: true,
    category: "Towels",
    description: "Oversized, ultra-plush Turkish cotton towel. The hallmark of resort lounging.",
  },
  {
    id: "prod_15",
    name: "Luxury Silk Swim Cap",
    price: 45,
    priceStr: "$45",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-900", "bg-[#e8dcc4]"],
    colorNames: ["Noir", "Sand"],
    isNew: false,
    category: "Swim Caps",
    description: "A high-end swim cap designed not to snag. Maintains hair integrity while swimming laps.",
  },

  // Eyewear, Hats, Footwear
  {
    id: "prod_16",
    name: "The Cannes Aviators",
    price: 310,
    priceStr: "$310",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-amber-900", "bg-stone-900"],
    colorNames: ["Tortoise", "Black"],
    isNew: true,
    category: "Sunglasses",
    description: "Premium polarized lenses housed in lightweight acetate frames. Uncompromising clarity and style.",
  },
  {
    id: "prod_17",
    name: "Performance Pool Goggles",
    price: 65,
    priceStr: "$65",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-500", "bg-[#0ea5e9]"],
    colorNames: ["Smoke", "Azure"],
    isNew: false,
    category: "Goggles",
    description: "Anti-fog, UV-protective professional swimming goggles with a sleek minimalist strap.",
  },
  {
    id: "prod_18",
    name: "The Mallorca Straw Boater",
    price: 195,
    priceStr: "$195",
    image: "/images/category_resortwear_1776341899337.png",
    images: ["/images/category_resortwear_1776341899337.png"],
    colors: ["bg-[#e8dcc4]"],
    colorNames: ["Natural"],
    isNew: false,
    category: "Hats",
    description: "Hand-woven from natural palm. Provides substantial shade with undeniable elegance.",
  },
  {
    id: "prod_19",
    name: "Cloud Pool Slides",
    price: 140,
    priceStr: "$140",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-900", "bg-white"],
    colorNames: ["Noir", "Blanc"],
    isNew: true,
    category: "Flip Flops",
    description: "Sculpted EVA foam step-in slides. Utterly weightless, completely waterproof.",
  },

  // Bags & Storage
  {
    id: "prod_20",
    name: "The Yacht Tote",
    price: 250,
    priceStr: "$250",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-[#c6a87c]"],
    colorNames: ["Canvas/Leather"],
    isNew: false,
    category: "Beach Bags",
    description: "Heavy-duty canvas and waterproof lining, trimmed with genuine vachetta leather.",
  },
  {
    id: "prod_21",
    name: "Silicone Waterproof Pouch",
    price: 55,
    priceStr: "$55",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-200"],
    colorNames: ["Translucent"],
    isNew: true,
    category: "Waterproof Bags",
    description: "Protect your valuables from the splash zone. Soft-touch silicone with a hermetic seal.",
  },

  // Pool Inflatables & Toys
  {
    id: "prod_22",
    name: "Oversized Minimalist Floatie",
    price: 90,
    priceStr: "$90",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-white", "bg-[#e8dcc4]"],
    colorNames: ["White", "Sand"],
    isNew: true,
    category: "Floaties",
    description: "A luxury pool float crafted from heavy-gauge matte vinyl.",
  },
  {
    id: "prod_23",
    name: "Classic Striped Pool Ring",
    price: 45,
    priceStr: "$45",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-red-400", "bg-blue-400"],
    colorNames: ["Coral/White", "Navy/White"],
    isNew: false,
    category: "Pool Rings",
    description: "A timeless striped pool ring that brings vintage Riviera aesthetics to any poolside.",
  },
  {
    id: "prod_24",
    name: "Kids Safety Arm Bands",
    price: 25,
    priceStr: "$25",
    image: "/images/category_kids_1776342027791.png",
    images: ["/images/category_kids_1776342027791.png"],
    colors: ["bg-orange-400"],
    colorNames: ["Safety Orange"],
    isNew: false,
    category: "Arm Bands",
    description: "Durable, high-buoyancy inflatable arm bands for the youngest swimmers.",
  },

  // Wellness & Accessories
  {
    id: "prod_25",
    name: "Broad Spectrum Mineral Sunscreen SPF 50",
    price: 48,
    priceStr: "$48",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-white"],
    colorNames: ["Standard 100ml"],
    isNew: true,
    category: "Sunscreen",
    description: "Reef-safe, invisible finish mineral sunscreen that deeply hydrates while protecting.",
  },
  {
    id: "prod_26",
    name: "Insulated Stainless Water Bottle",
    price: 60,
    priceStr: "$60",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-stone-900", "bg-[#e8dcc4]"],
    colorNames: ["Matte Black", "Matte Oat"],
    isNew: false,
    category: "Water Bottles",
    description: "Keeps beverages ice-cold for 24 hours under the hot summer sun. Ergonomic, sleek, and durable.",
  },
  {
    id: "prod_27",
    name: "Bamboo Poolside Deck Comb",
    price: 35,
    priceStr: "$35",
    image: "/images/category_pool_accessories_1776341916449.png",
    images: ["/images/category_pool_accessories_1776341916449.png"],
    colors: ["bg-[#c6a87c]"],
    colorNames: ["Natural Bamboo"],
    isNew: false,
    category: "Pool Accessories",
    description: "Perfect for detangling wet hair without breakage. Naturally anti-microbial bamboo.",
  }
];

export function getProductById(id: string): Product | undefined {
  return allProducts.find((p) => p.id === id);
}
